param(
    [switch] $Check
)

$ErrorActionPreference = "Stop"

$root = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$packagePath = Join-Path $root "package.json"
$outputPath = Join-Path $root "docs\generated\repo-map.md"

if (-not (Test-Path $packagePath)) {
    Write-Error "package.json not found."
}

$pkg = Get-Content -Raw $packagePath | ConvertFrom-Json
$dependencies = $pkg.dependencies
$devDependencies = $pkg.devDependencies
$scripts = $pkg.scripts

function Get-PropertyValue($object, $name, $fallback = "not detected") {
    if ($null -eq $object) {
        return $fallback
    }

    $property = $object.PSObject.Properties[$name]
    if ($null -eq $property) {
        return $fallback
    }

    return $property.Value
}

function Format-ScriptList($scriptsObject) {
    $items = @()
    foreach ($property in $scriptsObject.PSObject.Properties | Sort-Object Name) {
        $items += "- ``$($property.Name)``: ``$($property.Value)``"
    }
    return $items -join "`n"
}

function Format-PathList($paths) {
    if ($paths.Count -eq 0) {
        return "- none"
    }

    return ($paths | Sort-Object | ForEach-Object { "- ``$_``" }) -join "`n"
}

$topLevel = Get-ChildItem -Path $root -Force |
    Where-Object { $_.Name -notin @(".antigravitycli", ".git", ".next", ".omx", ".tmp", ".vscode", "node_modules", "tsconfig.tsbuildinfo", ".env.local") } |
    ForEach-Object {
        if ($_.PSIsContainer) {
            "$($_.Name)/"
        } else {
            $_.Name
        }
    }

$apiRoutes = @()
$apiRoot = Join-Path $root "src\app\api"
if (Test-Path $apiRoot) {
    $apiRoutes = Get-ChildItem -Path $apiRoot -Recurse -File -Filter route.ts |
        ForEach-Object { $_.FullName.Substring($root.Path.Length + 1).Replace("\", "/") }
}

$content = @"
# Generated Repo Map

Generated by ``scripts/harness/generate-repo-map.ps1``. Refresh with ``npm run harness:update-map``.

## Project

- Name: $($pkg.name)
- Version: $($pkg.version)
- Package manager: npm
- Framework: Next.js $(Get-PropertyValue $dependencies "next")
- React: $(Get-PropertyValue $dependencies "react")
- TypeScript: $(Get-PropertyValue $devDependencies "typescript")

## Scripts

$(Format-ScriptList $scripts)

## Top-Level Files And Directories

$(Format-PathList $topLevel)

## Source Areas

- ``src/app``: Next.js App Router pages, layout, loading state, and API routes.
- ``src/app/api``: admin, signal, database test, and diagnostic API endpoints.
- ``src/components``: dashboard UI components.
- ``src/components/v2``: current signal dashboard UI.
- ``src/hooks``: client-side signal configuration.
- ``src/lib``: database, external data clients, signal orchestration, and scoring.
- ``src/lib/types``: shared signal response types.

## API Routes

$(Format-PathList $apiRoutes)
"@

$normalizedContent = $content.TrimEnd() + "`r`n"

if ($Check) {
    if (-not (Test-Path $outputPath)) {
        Write-Error "Generated repo map is missing. Run npm run harness:update-map."
    }

    $existing = Get-Content -Raw $outputPath
    if ($existing -ne $normalizedContent) {
        Write-Error "Generated repo map is stale. Run npm run harness:update-map."
    }

    Write-Host "Generated repo map is current."
    exit 0
}

$outputDir = Split-Path -Parent $outputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

Set-Content -Path $outputPath -Value $normalizedContent -NoNewline
Write-Host "Updated docs/generated/repo-map.md."
