import type { ResearchWatchlistItem } from '@/components/research/ResearchDashboardV2';
import type { ResearchRecord } from '@/lib/types/research';

export const applyResearchRecordV6 = (item: ResearchWatchlistItem, record: ResearchRecord): ResearchWatchlistItem => ({
    ...item,
    name: record.companyName,
    market: record.market,
    positionState: record.positionState,
    inBuyZone: record.inBuyZone,
    status: record.status,
    targetBuyZone: record.targetBuyZone,
    valuationState: record.valuationState,
    thesisStrength: record.thesisStrength,
    lastReviewedAt: record.lastReviewedAt,
    whyInterested: record.whyInterested,
    bullCase: record.bullCase,
    bearCase: record.bearCase,
    buyTrigger: record.buyTrigger,
    sellTrigger: record.sellTrigger,
    thesisBreak: record.thesisBreak,
    checklist: record.checklist,
});

export const createWatchlistItemV6 = (record: ResearchRecord, order: number): ResearchWatchlistItem => applyResearchRecordV6({
    order,
    symbol: record.symbol,
    providerSymbol: record.market === 'US' ? `${record.symbol}.US` : `${record.symbol}.KLSE`,
    name: record.companyName,
    market: record.market,
    positionState: 'not-owned',
    inBuyZone: false,
    status: 'watch',
    targetBuyZone: '',
    valuationState: 'unknown',
    thesisStrength: 'medium',
    lastReviewedAt: record.lastReviewedAt,
    description: 'Provider profile not connected yet.',
    sector: 'Unknown',
    industry: 'Unknown',
    marketCap: 'Unknown',
    revenueGrowth: 'Unknown',
    grossMargin: 'Unknown',
    operatingMargin: 'Unknown',
    freeCashFlowTrend: 'Unknown',
    debtLevel: 'Unknown',
    cashPosition: 'Unknown',
    shareCountTrend: 'Unknown',
    whyInterested: '',
    bullCase: '',
    bearCase: '',
    buyTrigger: '',
    sellTrigger: '',
    thesisBreak: '',
    valuation: {
        pe: 'Unknown', forwardPe: 'Unknown', priceSales: 'Unknown', evEbitda: 'Unknown',
        fcfYield: 'Unknown', dividendYield: 'Unknown', fiveYearRange: 'Unknown', peerNote: 'Provider data unavailable.',
    },
    event: {
        nextEarnings: 'Unknown', lastEarnings: 'Unknown', revenueResult: 'Unknown', epsResult: 'Unknown',
        guidance: 'Provider data unavailable.', note: 'Add your event notes after reviewing a primary source.',
    },
    feed: [],
    technical: {
        ma50: 'Unknown', ma200: 'Unknown', range52Week: 'Unknown', rsi: 'Unknown',
        macd: 'Unknown', volume: 'Unknown', supportResistance: 'Unknown',
    },
    checklist: record.checklist,
}, record);

export const toResearchRecordV6 = (item: ResearchWatchlistItem, notes = ''): ResearchRecord => ({
    symbol: item.symbol,
    market: item.market,
    companyName: item.name,
    positionState: item.positionState,
    inBuyZone: item.inBuyZone,
    status: item.status,
    targetBuyZone: item.targetBuyZone,
    valuationState: item.valuationState,
    thesisStrength: item.thesisStrength,
    whyInterested: item.whyInterested,
    bullCase: item.bullCase,
    bearCase: item.bearCase,
    buyTrigger: item.buyTrigger,
    sellTrigger: item.sellTrigger,
    thesisBreak: item.thesisBreak,
    notes,
    checklist: item.checklist,
    lastReviewedAt: item.lastReviewedAt,
});
