import { chromium } from 'playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const baseUrlIndex = process.argv.findIndex((value) => value === '--base-url'); const baseUrl = (baseUrlIndex >= 0 ? process.argv[baseUrlIndex + 1] : process.env.SIGNAL_QA_BASE_URL || 'http://127.0.0.1:3000').replace(/\/$/, ''); const timeoutMs = Number(process.env.SIGNAL_QA_TIMEOUT_MS || 15000); const captureScreenshots = process.env.SIGNAL_QA_SCREENSHOTS !== '0'; const timestamp = new Date().toISOString().replace(/[:.]/g, '-'); const evidenceDir = path.resolve(process.env.SIGNAL_QA_EVIDENCE_DIR || path.join('.tmp', 'signal-learn-v0.4-qa', timestamp)); const viewports = [{ name: 'desktop', width: 1280, height: 800 }, { name: 'tablet', width: 768, height: 900 }, { name: 'mobile', width: 375, height: 812 }]; const report = { command: 'npm run qa:learn-v0.4', baseUrl, scenarios: [], fatalError: null };
const makeCandle = (index, close, future = false) => { const openTime = new Date(Date.UTC(2024, 3, 18, 9, 30 + index * 15)).toISOString(); const closeTime = new Date(Date.UTC(2024, 3, 18, 9, 45 + index * 15)).toISOString(); return { openTime, closeTime, open: close - 0.3, high: close + 0.6, low: close - 0.8, close, volume: 1000 + index * 100, knownAsOf: closeTime, future }; };
const introCandles = Array.from({ length: 12 }, (_, index) => makeCandle(index, 100 + Math.sin(index / 2) * 2 + index * 0.1)); const futureCandle = makeCandle(12, 777, true);
const replayIntro = { caseId: 'range-break-2024', replayId: 'range-break-fixture', symbol: 'EDU-A', timeframe: '15 minute', title: 'Range boundary fixture', contextKnownAsOf: introCandles.at(-1).knownAsOf, context: 'Price is testing a range boundary with no guaranteed continuation.', candles: introCandles, execution: { spread: 0.04, slippage: 0.03, fee: 1, note: 'Illustrative liquid execution.' }, sourceNote: 'Curated point-in-time fixture.' };
const addCheck = (scenario, name, passed, details = '') => { scenario.checks.push({ name, status: passed ? 'passed' : 'failed', details }); if (!passed) throw new Error(`${name}${details ? `: ${details}` : ''}`); };

const main = async () => { await mkdir(evidenceDir, { recursive: true }); let browser; try { browser = await chromium.launch({ headless: true }); for (const viewport of viewports) { const scenario = { viewport: `${viewport.width}x${viewport.height}`, checks: [], issues: [], screenshots: [], status: 'failed' }; report.scenarios.push(scenario); const context = await browser.newContext({ viewport: { width: viewport.width, height: viewport.height } }); await context.addInitScript(() => { if (!sessionStorage.getItem('signal-learn-v0.4-qa-init')) { localStorage.removeItem('signal-learn-v0.4-progress'); localStorage.removeItem('signal-learn-v0.4-trade-journal'); sessionStorage.setItem('signal-learn-v0.4-qa-init', '1'); } }); const page = await context.newPage(); page.setDefaultTimeout(timeoutMs); const advanceBodies = [];
        page.on('console', (message) => { if (message.type() === 'error') scenario.issues.push({ type: 'console-error', message: message.text() }); }); page.on('pageerror', (error) => scenario.issues.push({ type: 'page-error', message: error.message })); page.on('requestfailed', (request) => scenario.issues.push({ type: 'request-failed', message: `${request.method()} ${request.url()}` }));
        await page.route('**/api/learn/trading-replay/**', async (route) => { if (route.request().method() === 'POST') { advanceBodies.push(route.request().postDataJSON()); await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ success: true, data: { candle: futureCandle, complete: true, debrief: ['Process used a complete No Trade decision.', 'P&L is not the score.'] } }) }); } else await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ success: true, data: replayIntro }) }); });
        try { const response = await page.goto(`${baseUrl}/learn`, { waitUntil: 'domcontentloaded' }); addCheck(scenario, 'learn route response', response?.ok() === true, response ? `HTTP ${response.status()}` : 'no response'); await page.getByTestId('learn-v0-4').waitFor(); addCheck(scenario, 'v0.4 is current release', await page.getByRole('button', { name: 'Trading process v0.4' }).getAttribute('aria-pressed') === 'true'); const primary = page.locator('nav[aria-label^="Primary"]:visible'); addCheck(scenario, 'shared Learn navigation remains selected', (await primary.locator('a[aria-current="page"]').textContent())?.trim() === 'Learn'); let overflow = await page.evaluate(() => Math.max(document.body.scrollWidth, document.documentElement.scrollWidth) - innerWidth); addCheck(scenario, 'initial page has no horizontal overflow', overflow <= 1, `${overflow}px`); if (captureScreenshots) { const file = path.join(evidenceDir, `learn-v0.4-${viewport.name}-light.png`); await page.screenshot({ path: file, fullPage: true }); scenario.screenshots.push(file); }

            const conceptSize = await page.getByTestId('trading-concept').evaluate((element) => ({ clientWidth: element.clientWidth, scrollWidth: element.scrollWidth })); addCheck(scenario, 'concept panel contains its mobile content', conceptSize.scrollWidth <= conceptSize.clientWidth + 1, `${conceptSize.scrollWidth}/${conceptSize.clientWidth}`); await page.getByLabel('Trading concept reasoning').fill('Price structure needs context, a limitation, and observable invalidation.'); await page.getByRole('button', { name: 'Mark understood' }).click(); addCheck(scenario, 'concept mastery updates', (await page.getByTestId('trading-mastery').innerText()).includes('1/16'));
            await page.getByRole('button', { name: /^Price lab/ }).click(); const chartLab = page.getByTestId('trading-chart-lab'); const chart = chartLab.getByTestId('trading-candle-chart'); await chart.waitFor(); const box = await chart.boundingBox(); addCheck(scenario, 'chart remains readable and contained', Boolean(box && box.height >= 200 && box.width <= viewport.width)); addCheck(scenario, 'SMA EMA and VWAP are contextual overlays', await chartLab.getByTestId('sma-line').count() === 1 && await chartLab.getByTestId('ema-line').count() === 1 && await chartLab.getByTestId('vwap-line').count() === 1); await page.getByRole('button', { name: 'Range / transition' }).click(); await page.getByRole('button', { name: 'Reveal annotation' }).click(); addCheck(scenario, 'structure is classified before reveal', (await page.getByTestId('structure-reveal').innerText()).includes('changes regime')); const smaBefore = await chartLab.getByTestId('sma-line').getAttribute('points'); await page.getByLabel('SMA lookback').fill('20'); addCheck(scenario, 'moving-average lookback changes the same history', await chartLab.getByTestId('sma-line').getAttribute('points') !== smaBefore); await page.getByRole('button', { name: 'Complete chart lab' }).click();
            await page.getByRole('button', { name: /^Trade plan/ }).click(); for (const [label, value] of [['Plan Context', 'Broad market is range-bound.'], ['Plan Setup', 'Price tests a reaction zone.'], ['Plan Trigger', 'Close and retest above the zone.'], ['Plan Time horizon', 'One to three sessions.']]) await page.getByLabel(label).fill(value); await page.getByRole('button', { name: 'Save construction exercise' }).click(); addCheck(scenario, 'trade construction requires complete process fields', (await page.getByTestId('trading-mastery').innerText()).includes('2/8'));
            await page.getByRole('button', { name: /^Risk/ }).click(); const riskCalculator = page.getByTestId('risk-calculator'); const sizeBefore = await page.getByTestId('risk-position-size').textContent(); await page.getByLabel('Invalidation / stop').fill('95'); addCheck(scenario, 'position size recomputes with stop distance', await page.getByTestId('risk-position-size').textContent() !== sizeBefore); await page.getByLabel('Risk direction').selectOption('short'); addCheck(scenario, 'invalid short stop direction is explicit', (await riskCalculator.getByRole('alert').innerText()).includes('short invalidation')); await page.getByLabel('Risk direction').selectOption('long'); await page.getByRole('button', { name: 'Complete risk exercise' }).click();
            await page.getByRole('button', { name: /^Expectancy/ }).click(); const expectancyText = await page.getByTestId('expectancy-lab').innerText(); addCheck(scenario, 'expectancy is distinct from win rate', expectancyText.includes('-0.07R') && expectancyText.includes('0.49R')); await page.getByRole('button', { name: 'Complete expectancy exercise' }).click();

            await page.getByRole('button', { name: /^Replay/ }).click(); const replay = page.getByTestId('trading-replay'); await page.getByTestId('trading-replay-locked').waitFor(); addCheck(scenario, 'future candle is absent before commitment', !(await page.locator('main').innerText()).includes('777')); await page.getByRole('button', { name: 'No Trade', exact: true }).click(); await page.getByLabel('Replay Context').fill('Range boundary has uncertain continuation.'); await page.getByLabel('Replay Setup').fill('No complete trigger is present.'); await page.getByLabel('Replay Time horizon').fill('Intraday observation.'); await page.getByLabel('Replay reason not to trade').fill('Spread and trigger quality do not justify planned risk.'); await page.getByRole('button', { name: 'Commit replay decision' }).click(); addCheck(scenario, 'No Trade is accepted and locked', await replay.getByText(/Original decision locked.*No Trade/).count() === 1); await page.getByRole('button', { name: 'Next candle' }).click(); await page.getByTestId('trading-replay-debrief').waitFor(); addCheck(scenario, 'replay POST carries a complete No Trade decision', advanceBodies[0]?.commitment?.decision === 'no-trade' && Boolean(advanceBodies[0]?.commitment?.reasonNoTrade)); addCheck(scenario, 'future candle appears only after advance', (await replay.getByTestId('trading-candle-chart').locator('svg').innerHTML()).includes('777')); addCheck(scenario, 'debrief scores process rather than P&L', (await page.getByTestId('trading-replay-debrief').innerText()).includes('P&L is not the score'));
            await page.getByRole('button', { name: /^Strategy Lab/ }).click(); const strategyText = (await page.getByTestId('strategy-lab').innerText()).toLowerCase(); addCheck(scenario, 'backtest exposes sample costs drawdown and robustness', strategyText.includes('samples') && strategyText.includes('costs') && strategyText.includes('max drawdown') && strategyText.includes('parameter sensitivity')); await page.getByLabel('Fees bps').fill('0'); await page.getByLabel('Slippage bps').fill('0'); addCheck(scenario, 'missing costs produce a warning', (await page.getByTestId('strategy-lab').innerText()).includes('Missing transaction-cost assumptions')); await page.getByRole('button', { name: 'Complete strategy exercise' }).click(); await page.getByRole('button', { name: /^Replay/ }).click(); addCheck(scenario, 'replay state survives panel switching', await page.getByTestId('trading-replay-debrief').count() === 1);

            await page.getByRole('button', { name: /^Trade Journal/ }).click(); for (const [label, value] of [['Journal Context', 'Market is range-bound.'], ['Journal Setup', 'Retest setup with defined zone.'], ['Journal Trigger', 'Close above the reaction area.'], ['Journal Time horizon', 'Two sessions.']]) await page.getByLabel(label).fill(value); await page.getByRole('button', { name: 'Commit pre-trade plan' }).click(); addCheck(scenario, 'original pre-trade plan is immutable', (await page.getByTestId('trade-journal-original').innerText()).includes('Market is range-bound.')); await page.getByLabel('Journal event reason').fill('No new evidence; original invalidation remains valid.'); await page.getByRole('button', { name: 'Append event' }).click(); addCheck(scenario, 'trade management event appends', (await page.getByTestId('trade-journal').innerText()).includes('No new evidence'));
            await page.getByRole('button', { name: /^Practice/ }).click(); await page.getByLabel('Current context').fill('Delayed context shows a range; no action is required.'); await page.getByRole('button', { name: 'Complete practice' }).click(); addCheck(scenario, 'observe-only current practice is valid', (await page.getByTestId('trading-practice').innerText()).toLowerCase().includes('observe only available'));

            await page.reload({ waitUntil: 'domcontentloaded' }); await page.getByTestId('trading-mastery').waitFor(); await page.waitForFunction(() => document.querySelector('[data-testid="trading-mastery"]')?.textContent?.includes('1/16')); addCheck(scenario, 'v0.4 progress persists independently', (await page.getByTestId('trading-mastery').innerText()).includes('1/16')); await page.getByRole('button', { name: /^Trade Journal/ }).click(); await page.getByTestId('trade-journal-original').waitFor(); addCheck(scenario, 'immutable trade journal persists after reload', (await page.getByTestId('trade-journal-original').innerText()).includes('Market is range-bound.'));
            await page.getByRole('button', { name: 'Investment analysis v0.3' }).click(); addCheck(scenario, 'v0.3 remains reachable', await page.getByTestId('learn-v0-3').count() === 1); await page.getByRole('button', { name: 'Business foundations v0.2' }).click(); addCheck(scenario, 'v0.2 remains reachable', await page.getByTestId('learn-v0-2').count() === 1); await page.getByRole('button', { name: 'Valuation foundations v0.1' }).click(); addCheck(scenario, 'v0.1 remains reachable', await page.getByTestId('learn-v0-1').count() === 1); await page.getByRole('button', { name: 'Trading process v0.4' }).click();
            const themeButton = page.locator('button[aria-label^="Switch to"]'); const shell = page.getByTestId('learn-shell'); const beforeTheme = await shell.getAttribute('data-theme'); await themeButton.click(); addCheck(scenario, 'theme toggle remains functional', await shell.getAttribute('data-theme') !== beforeTheme); overflow = await page.evaluate(() => Math.max(document.body.scrollWidth, document.documentElement.scrollWidth) - innerWidth); addCheck(scenario, 'completed flow has no horizontal overflow', overflow <= 1, `${overflow}px`); if (captureScreenshots) { const file = path.join(evidenceDir, `learn-v0.4-${viewport.name}-dark.png`); await page.screenshot({ path: file, fullPage: true }); scenario.screenshots.push(file); } addCheck(scenario, 'no browser errors', scenario.issues.length === 0, JSON.stringify(scenario.issues)); scenario.status = 'passed';
        } catch (error) { scenario.issues.push({ type: 'blocking', message: error instanceof Error ? error.message : String(error) }); } finally { await context.close(); }
    } } catch (error) { report.fatalError = error instanceof Error ? error.message : String(error); } finally { if (browser) await browser.close(); await writeFile(path.join(evidenceDir, 'report.json'), JSON.stringify(report, null, 2)); } const failed = Boolean(report.fatalError) || report.scenarios.some((scenario) => scenario.status !== 'passed'); console.log(JSON.stringify({ evidenceDir, scenarios: report.scenarios.map(({ viewport, status, issues }) => ({ viewport, status, issues })), fatalError: report.fatalError }, null, 2)); if (failed) process.exitCode = 1; };
await main();
