'use client';

import { useEffect, useMemo, useState } from 'react';
import {
    calculateMultipleChangeV03,
    investmentModulesV03,
    type InvestmentModuleIdV03,
} from '@/lib/learn/v0-3';

const progressKey = 'signal-learn-v0.3-progress';

const Card = ({ title, children, tone = 'default' }: { readonly title: string; readonly children: React.ReactNode; readonly tone?: 'default' | 'accent' | 'risk' | 'caution' }) => {
    const classes = tone === 'accent' ? 'border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)]'
        : tone === 'risk' ? 'border-[var(--v7-risk)] bg-[var(--v7-risk-quiet)]'
            : tone === 'caution' ? 'border-[var(--v7-caution)] bg-[var(--v7-caution-quiet)]'
                : 'border-[var(--v7-border)] bg-[var(--v7-surface-quiet)]';
    return <article className={`rounded-[11px] border p-4 ${classes}`}><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-[var(--v7-text-muted)]">{title}</p><div className="mt-2 text-sm leading-6 text-[var(--v7-text-secondary)]">{children}</div></article>;
};

const Input = ({ label, value, onChange, suffix }: { readonly label: string; readonly value: number; readonly onChange: (value: number) => void; readonly suffix?: string }) => <label className="grid gap-1.5 text-xs font-semibold text-[var(--v7-text-secondary)]">{label}<span className="flex min-h-10 items-center rounded-[9px] border border-[var(--v7-border)] px-3 focus-within:border-[var(--v7-accent)]"><input type="number" value={value} onChange={(event) => onChange(Number(event.target.value))} className="min-w-0 flex-1 bg-transparent font-mono text-sm text-[var(--v7-text)] outline-none" />{suffix ? <span className="ml-1 text-[var(--v7-text-muted)]">{suffix}</span> : null}</span></label>;
const fmt = (value: number | null, suffix = '') => value === null ? 'N/A' : `${new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 }).format(value)}${suffix}`;

const MultipleLab = () => {
    const [startEps, setStartEps] = useState(5);
    const [startMultiple, setStartMultiple] = useState(30);
    const [endEps, setEndEps] = useState(7);
    const [endMultiple, setEndMultiple] = useState(20);
    const result = calculateMultipleChangeV03(startEps, startMultiple, endEps, endMultiple);
    return <div data-testid="multiple-change-lab" className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_290px]"><div><div className="grid gap-3 sm:grid-cols-2"><Input label="Starting EPS" value={startEps} onChange={setStartEps} /><Input label="Starting P/E" value={startMultiple} onChange={setStartMultiple} suffix="×" /><Input label="Ending EPS" value={endEps} onChange={setEndEps} /><Input label="Ending P/E" value={endMultiple} onChange={setEndMultiple} suffix="×" /></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{[
        ['Starting implied price', `$${fmt(result.startingPrice)}`], ['Ending implied price', `$${fmt(result.endingPrice)}`], ['Price change', fmt(result.priceChangePercent, '%')], ['Earnings change', fmt(result.earningsChangePercent, '%')], ['Multiple change', fmt(result.multipleChangePercent, '%')],
    ].map(([label, value]) => <div key={label} className="rounded-[9px] border border-[var(--v7-border)] bg-[var(--v7-surface-quiet)] p-3"><p className="text-[11px] text-[var(--v7-text-muted)]">{label}</p><p className="mt-1 font-mono text-sm font-bold text-[var(--v7-text)]">{value}</p></div>)}</div></div><Card title="What this teaches" tone="accent">Earnings can rise while the stock performs poorly if the valuation multiple compresses enough. Business performance and the price investors are willing to pay are separate drivers.</Card></div>;
};

const Frameworks = () => <div className="grid gap-3 sm:grid-cols-2"><Card title="P/E">Useful when positive earnings are reasonably representative. Weak when earnings are cyclical, temporarily distorted, or negative.</Card><Card title="Price / sales">Can help when earnings are immature, but sales have no value without eventual margins and cash generation.</Card><Card title="EV / EBITDA">Can improve capital-structure comparison in some industries, but ignores CapEx and can still hide economic differences.</Card><Card title="FCF yield" tone="accent">Connects price to cash generation. Still requires judging whether current cash flow is sustainable and how much reinvestment the business needs.</Card></div>;

const ConceptCards = ({ id }: { readonly id: InvestmentModuleIdV03 }) => {
    if (id === 'valuation-frameworks') return <Frameworks />;
    if (id === 'multiple-change') return <MultipleLab />;
    if (id === 'business-quality') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Quality evidence" tone="accent">Switching costs, network effects, scale, recurring revenue, customer retention, and attractive capital efficiency can support durable economics.</Card><Card title="Quality ≠ attractive price" tone="risk">A great business can still be a poor investment if the valuation requires unrealistic growth or leaves no margin for error.</Card><Card title="Concentration">Customer, supplier, product, or geographic concentration can make apparently strong economics fragile.</Card><Card title="Capital intensity">Ask how much incremental capital is needed to create incremental profit. Growth that consumes enormous capital is different from high-return compounding.</Card></div>;
    if (id === 'capital-allocation') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Reinvest">Best when the company can deploy capital at attractive incremental returns.</Card><Card title="Buybacks">Potentially valuable when shares are repurchased below reasonable value; potentially destructive when management overpays.</Card><Card title="Debt / dividends">Both compete with reinvestment and buybacks for capital. Judge them through balance-sheet resilience and opportunity cost.</Card><Card title="Acquisitions" tone="caution">Revenue growth from M&A is not automatically value creation. Ask what was paid, how it was financed, and whether returns exceed the cost of capital.</Card></div>;
    if (id === 'rates-yields') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Required return" tone="accent">When safer yields rise, investors may demand a higher expected return from equities. That can reduce the multiple they are willing to pay.</Card><Card title="Duration intuition">Businesses whose expected cash flows sit far in the future can be more valuation-sensitive to changes in required returns.</Card><Card title="No mechanical rule" tone="risk">Rising Treasury yields do not guarantee stocks fall. Earnings expectations, inflation, growth, risk premiums, and positioning can move at the same time.</Card><Card title="Evidence habit">Separate the observed yield change from your interpretation of why it changed and from your forecast of what it will do next.</Card></div>;
    if (id === 'inflation-cycle') return <div className="grid gap-3 sm:grid-cols-2"><Card title="First-order result">Inflation, employment, PMI, and GDP are measurements—not automatic bullish/bearish labels.</Card><Card title="Second-order effect" tone="accent">A strong jobs report can support earnings expectations yet also push expected rates higher. Ask which channel matters more to the asset being valued.</Card><Card title="Business exposure">Pricing power, input costs, debt refinancing, consumer sensitivity, and cyclicality determine how macro changes reach company economics.</Card><Card title="Do not threshold trade" tone="risk">Avoid rules such as “PMI below X means sell.” Regime, expectations, and valuation context matter.</Card></div>;
    if (id === 'narrative') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Decompose sentiment" tone="accent">Look separately at news themes, estimate direction when available, price momentum, sector behavior, volatility, and positioning rather than one opaque score.</Card><Card title="Narrative is evidence about belief">A popular story tells you what participants may care about. It does not prove the story is economically correct.</Card><Card title="Narrative shift">The relevant question is often what changed in the story or expectations—not whether headlines sound positive or negative in isolation.</Card><Card title="Source discipline" tone="risk">Retrospective narratives must never be used as point-in-time evidence in historical replay.</Card></div>;
    if (id === 'catalysts') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Catalyst" tone="accent">An event—earnings, product launch, regulation, investor day, M&A, macro release—that may change expectations.</Card><Card title="Thesis">The broader explanation of business economics, valuation, expectations, risks, and what would invalidate your view.</Card><Card title="Catalyst without thesis">A product launch can move a stock without making the long-term business attractive.</Card><Card title="Thesis without catalyst">A compounding business may create value without one near-term event. Do not confuse “nothing happening soon” with “no investment case.”</Card></div>;
    if (id === 'thesis') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Required structure" tone="accent">Business → quality → growth → valuation → expectations → risks → contrary evidence → invalidation → confidence.</Card><Card title="Falsifiability">A thesis that cannot describe what would make it wrong is a story, not a testable decision framework.</Card><Card title="Contrary evidence">Signal requires evidence against the view so the learner cannot complete a thesis using only confirmation.</Card><Card title="Practice">Use Apply Today to build and save a practice thesis from current evidence.</Card></div>;
    if (id === 'scenarios') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Bear / Base / Bull" tone="accent">Each scenario should state its earnings or cash-flow assumption, valuation assumption, probability, and the evidence that could lead there.</Card><Card title="Probability discipline">Probabilities are explicit and must sum to 100%. Signal does not silently normalize them.</Card><Card title="Ranges, not certainty">An implied value is conditional on assumptions. It is not a fact or guaranteed target.</Card><Card title="Practice">Use Apply Today to edit all three scenarios and see which assumptions dominate the result.</Card></div>;
    if (id === 'portfolio') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Diversification">Ten tickers can still represent one concentrated economic bet if they share the same factor or industry exposure.</Card><Card title="Position sizing" tone="accent">Size should reflect risk capacity, uncertainty, concentration, and portfolio interactions—not excitement about the thesis.</Card><Card title="Correlation">Assets that usually move together can reduce the diversification benefit of holding both.</Card><Card title="Rebalancing">Rebalancing changes exposures. It is not automatically a prediction that recent winners will reverse.</Card></div>;
    if (id === 'risk') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Volatility">Price variability matters for sizing and behavior, but it is not the whole concept of investment risk.</Card><Card title="Permanent loss" tone="risk">Business impairment, excessive debt, dilution, overpayment, fraud, or structural decline can permanently destroy capital.</Card><Card title="Thesis risk">The core assumptions may simply be wrong even when the company remains healthy.</Card><Card title="Liquidity / concentration">The ability to exit and the amount exposed to one idea can materially change portfolio risk.</Card></div>;
    if (id === 'behavior') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Confirmation bias">Searching only for supportive evidence. Countermeasure: require contrary evidence before commitment.</Card><Card title="Anchoring">Treating an old price or estimate as inherently meaningful. Countermeasure: re-evaluate using current economics.</Card><Card title="FOMO / recency">Overweighting recent moves or stories because they feel urgent. Countermeasure: state the thesis and horizon before acting.</Card><Card title="Outcome bias" tone="risk">A profitable decision can still be poorly reasoned. A loss can still come from a sound probabilistic process.</Card></div>;
    return <div className="grid gap-3 sm:grid-cols-2"><Card title="Original entry" tone="accent">Record the thesis, contrary evidence, invalidation, scenario assumptions, confidence, and timestamp before the outcome is known.</Card><Card title="Append updates">Later evidence is appended as a new reflection. The original entry stays unchanged.</Card><Card title="No historical rewrite" tone="risk">Do not edit the old thesis to make it look closer to what later happened.</Card><Card title="Practice">Apply Today includes a browser-local practice journal that does not mutate your main Research records.</Card></div>;
};

export const InvestmentTrackV3 = () => {
    const [moduleId, setModuleId] = useState<InvestmentModuleIdV03>('valuation-frameworks');
    const [completed, setCompleted] = useState<InvestmentModuleIdV03[]>([]);
    const [ready, setReady] = useState(false);
    useEffect(() => {
        const timer = window.setTimeout(() => {
            try {
                const parsed: unknown = JSON.parse(window.localStorage.getItem(progressKey) ?? '[]');
                if (Array.isArray(parsed)) setCompleted(parsed.filter((value): value is InvestmentModuleIdV03 => typeof value === 'string' && investmentModulesV03.some((item) => item.id === value)));
            } catch { setCompleted([]); }
            setReady(true);
        }, 0);
        return () => window.clearTimeout(timer);
    }, []);
    useEffect(() => { if (ready) window.localStorage.setItem(progressKey, JSON.stringify(completed)); }, [completed, ready]);
    const selected = useMemo(() => investmentModulesV03.find((item) => item.id === moduleId) ?? investmentModulesV03[0], [moduleId]);
    const toggle = () => setCompleted((current) => current.includes(moduleId) ? current.filter((id) => id !== moduleId) : [...current, moduleId]);
    return <div data-testid="investment-track-v3" className="grid gap-4 lg:grid-cols-[270px_minmax(0,1fr)]"><aside className="min-w-0 rounded-[11px] border border-[var(--v7-border)] bg-[var(--v7-surface-quiet)] p-3 lg:self-start"><div className="flex items-center justify-between px-2 pb-2"><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-[var(--v7-text-muted)]">v0.3 path</p><span className="font-mono text-[11px] text-[var(--v7-text-muted)]">{completed.length}/{investmentModulesV03.length}</span></div><div className="research-scrollbar flex gap-2 overflow-x-auto lg:grid lg:overflow-visible">{investmentModulesV03.map((item) => <button key={item.id} type="button" aria-pressed={item.id === moduleId} onClick={() => setModuleId(item.id)} className={`min-h-11 min-w-[220px] rounded-[9px] border px-3 py-2 text-left lg:min-w-0 ${item.id === moduleId ? 'border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)]' : 'border-transparent hover:border-[var(--v7-border)] hover:bg-[var(--v7-surface)]'}`}><span className="flex items-center justify-between gap-2"><span className="text-xs font-semibold text-[var(--v7-text)]">{item.eyebrow} · {item.title}</span><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${completed.includes(item.id) ? 'bg-[var(--v7-accent)]' : 'border border-[var(--v7-border-strong)]'}`} /></span></button>)}</div></aside><section className="rounded-[11px] border border-[var(--v7-border)] bg-[var(--v7-surface)] p-4 sm:p-5 lg:p-6"><div className="flex flex-col gap-4 border-b border-[var(--v7-border)] pb-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.12em] text-[var(--v7-accent)]">Module {selected.eyebrow}</p><h2 className="mt-1 text-xl font-bold text-[var(--v7-text)]">{selected.title}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-[var(--v7-text-secondary)]">{selected.objective}</p></div><button type="button" aria-pressed={completed.includes(moduleId)} onClick={toggle} className={`min-h-10 rounded-[9px] border px-4 text-sm font-semibold ${completed.includes(moduleId) ? 'border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)]' : 'border-[var(--v7-border)] text-[var(--v7-text-secondary)]'}`}>{completed.includes(moduleId) ? 'Understood ✓' : 'Mark understood'}</button></div><div className="pt-5"><ConceptCards id={moduleId} /></div></section></div>;
};
