'use client';

import { useEffect, useMemo, useState } from 'react';
import { type InvestmentReplayCommitmentV03, type LearnReflectionV03 } from '@/lib/learn/v0-3';

type CaseId = 'duration-reset-2022' | 'cyclical-peak-2021';
type Snapshot = { revenueGrowth: string; margin: string; earningsPower: string; valuation: string; estimates: string; rates: string; inflation: string; events: readonly string[]; narrativeEvidence: readonly string[] };
type Intro = { caseId: CaseId; replayId: string; title: string; knownAsOf: string; setup: string; snapshot: Snapshot; sourceNote: string };
type Reveal = Intro & { nextKnownAsOf: string; nextSnapshot: Snapshot; debrief: readonly string[] };

const cases: readonly { id: CaseId; label: string; note: string }[] = [
    { id: 'duration-reset-2022', label: 'Duration reset', note: 'Growth, estimates, and yields' },
    { id: 'cyclical-peak-2021', label: 'Cyclical peak', note: 'Margins, capital allocation, and normalization' },
];
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const readPayload = <T,>(value: unknown): T => { if (!isRecord(value) || value.success !== true || !isRecord(value.data)) throw new Error(isRecord(value) && typeof value.error === 'string' ? value.error : 'Investment Replay is unavailable.'); return value.data as T; };
const fieldClass = 'min-h-10 w-full rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] px-3 text-sm text-[var(--v7-text)]';
const labelClass = 'grid gap-1.5 text-xs font-semibold text-[var(--v7-text-secondary)]';

const SnapshotView = ({ snapshot }: { snapshot: Snapshot }) => <div className="grid gap-px overflow-hidden rounded-[8px] border border-[var(--v7-border)] bg-[var(--v7-border)] sm:grid-cols-2 xl:grid-cols-4">{[
    ['Revenue growth', snapshot.revenueGrowth], ['Margin', snapshot.margin], ['Earnings power', snapshot.earningsPower], ['Valuation', snapshot.valuation], ['Estimates / revisions', snapshot.estimates], ['Rates / yields', snapshot.rates], ['Inflation', snapshot.inflation], ['Contemporaneous events', snapshot.events.join(' ')],
].map(([label, value]) => <article key={label} className="bg-[var(--v7-surface-quiet)] p-3"><p className="text-[10px] font-bold uppercase text-[var(--v7-text-muted)]">{label}</p><p className="mt-2 text-xs leading-5 text-[var(--v7-text)]">{value}</p></article>)}</div>;

export const LearnInvestmentReplayV3 = ({ completedCaseIds, onReflectionSave }: { readonly completedCaseIds: readonly string[]; readonly onReflectionSave: (reflection: LearnReflectionV03) => void }) => {
    const [caseId, setCaseId] = useState<CaseId>('duration-reset-2022');
    const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading');
    const [intro, setIntro] = useState<Intro | null>(null); const [reveal, setReveal] = useState<Reveal | null>(null); const [error, setError] = useState('');
    const [scenario, setScenario] = useState<InvestmentReplayCommitmentV03['scenario']>('uncertain'); const [confidence, setConfidence] = useState(50); const [thesis, setThesis] = useState(''); const [support, setSupport] = useState(''); const [against, setAgainst] = useState(''); const [invalidation, setInvalidation] = useState('');
    const [heldUp, setHeldUp] = useState(''); const [missed, setMissed] = useState(''); const [change, setChange] = useState('');
    useEffect(() => { const controller = new AbortController(); const load = async () => { setState('loading'); setIntro(null); setReveal(null); setError(''); setThesis(''); setSupport(''); setAgainst(''); setInvalidation(''); try { const response = await fetch(`/api/learn/investment-replay/${caseId}`, { cache: 'no-store', signal: controller.signal }); const payload: unknown = await response.json(); if (!response.ok) throw new Error(isRecord(payload) && typeof payload.error === 'string' ? payload.error : 'Investment Replay is unavailable.'); setIntro(readPayload<Intro>(payload)); setState('ready'); } catch (caught) { if (controller.signal.aborted) return; setError(caught instanceof Error ? caught.message : 'Investment Replay is unavailable.'); setState('error'); } }; void load(); return () => controller.abort(); }, [caseId]);
    const commitment = useMemo<InvestmentReplayCommitmentV03>(() => ({ thesis: thesis.trim(), scenario, supportingEvidence: support.trim(), contraryEvidence: against.trim(), invalidation: invalidation.trim(), confidence }), [against, confidence, invalidation, scenario, support, thesis]);
    const ready = [commitment.thesis, commitment.supportingEvidence, commitment.contraryEvidence, commitment.invalidation].every((value) => value.length >= 8);
    const revealNext = async (event: React.FormEvent) => { event.preventDefault(); if (!intro || !ready) return; const response = await fetch(`/api/learn/investment-replay/${caseId}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ replayId: intro.replayId, commitment }) }); const payload: unknown = await response.json(); if (!response.ok) { setError(isRecord(payload) && typeof payload.error === 'string' ? payload.error : 'Reveal failed.'); return; } setReveal(readPayload<Reveal>(payload)); };
    const save = () => { if (!heldUp.trim() || !missed.trim() || !change.trim()) return; onReflectionSave({ caseId, heldUp: heldUp.trim(), missed: missed.trim(), thesisChange: change.trim() }); };
    return <section data-testid="investment-replay"><div className="grid gap-2 sm:grid-cols-2" aria-label="Investment replay cases">{cases.map((item) => <button key={item.id} type="button" aria-pressed={caseId === item.id} onClick={() => setCaseId(item.id)} className={`min-h-11 rounded-[8px] border p-3 text-left ${caseId === item.id ? 'border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)]' : 'border-[var(--v7-border)]'}`}><span className="block text-sm font-bold">{item.label}</span><span className="mt-1 block text-xs text-[var(--v7-text-muted)]">{item.note}</span></button>)}</div>
        <div className="mt-5"><p className="text-[11px] font-bold uppercase text-[var(--v7-accent)]">Point-in-time Investment Replay</p><h2 className="mt-2 text-xl font-bold text-[var(--v7-text)]">Commit the thesis before the next checkpoint appears.</h2><p className="mt-2 text-sm leading-6 text-[var(--v7-text-secondary)]">Financials, valuation, estimates, macro, yields, and events are bounded by the known-as-of date. Retrospective narrative is excluded from the pre-commitment view.</p></div>
        {state === 'loading' && <p role="status" className="mt-4 border border-[var(--v7-border)] p-4 text-sm">Loading point-in-time evidence...</p>}{state === 'error' && <p role="alert" className="mt-4 border border-red-500 p-4 text-sm text-red-600">{error}</p>}
        {state === 'ready' && intro && <><div data-testid="investment-replay-locked" className="mt-4 rounded-[8px] border border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)] p-4"><p className="text-xs font-bold uppercase text-[var(--v7-accent)]">Future checkpoint locked · known as of {intro.knownAsOf}</p><h3 className="mt-2 font-bold">{intro.title}</h3><p className="mt-2 text-sm leading-6 text-[var(--v7-text-secondary)]">{intro.setup}</p><p className="mt-2 text-xs text-[var(--v7-text-muted)]">{intro.sourceNote}</p></div><div className="mt-3"><SnapshotView snapshot={intro.snapshot} /></div><div className="mt-3 rounded-[6px] border border-[var(--v7-border)] p-3"><p className="text-[10px] font-bold uppercase text-[var(--v7-text-muted)]">Observable narrative evidence</p><ul className="mt-2 grid gap-1 text-xs leading-5">{intro.snapshot.narrativeEvidence.map((item) => <li key={item}>- {item}</li>)}</ul></div>
            {!reveal && <form onSubmit={revealNext} className="mt-5 border-t border-[var(--v7-border)] pt-5"><div className="grid gap-3 md:grid-cols-2"><label className={labelClass}>Scenario<select aria-label="Replay scenario" className={fieldClass} value={scenario} onChange={(event) => setScenario(event.target.value as InvestmentReplayCommitmentV03['scenario'])}><option value="bear">Bear</option><option value="base">Base</option><option value="bull">Bull</option><option value="uncertain">Uncertain</option></select></label><label className={labelClass}>Confidence: {confidence}%<input aria-label="Replay confidence" type="range" min="0" max="100" value={confidence} onChange={(event) => setConfidence(Number(event.target.value))} /></label>{[['Replay thesis', thesis, setThesis], ['Supporting evidence', support, setSupport], ['Contrary evidence', against, setAgainst], ['Invalidation', invalidation, setInvalidation]].map(([label, value, setter]) => <label key={label as string} className={labelClass}>{label as string}<textarea aria-label={label as string} className="min-h-24 rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] p-3 text-sm" value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)} /></label>)}</div><button type="submit" disabled={!ready} className="mt-4 min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white disabled:opacity-40">Commit thesis and reveal</button></form>}
            {reveal && <div data-testid="investment-replay-revealed" className="mt-5 grid gap-4"><div className="rounded-[8px] border border-[var(--v7-border)] bg-[var(--v7-surface-quiet)] p-4"><p className="text-xs font-bold uppercase text-[var(--v7-accent)]">Original commitment locked</p><p className="mt-2 text-sm">{commitment.scenario} at {commitment.confidence}% confidence: {commitment.thesis}</p></div><div className="rounded-[8px] border border-[var(--v7-accent)] p-4"><p className="text-xs font-bold uppercase text-[var(--v7-accent)]">Next checkpoint · known as of {reveal.nextKnownAsOf}</p><div className="mt-3"><SnapshotView snapshot={reveal.nextSnapshot} /></div><ul className="mt-3 grid gap-1 text-xs leading-5">{reveal.debrief.map((item) => <li key={item}>- {item}</li>)}</ul></div><div className="grid gap-3 md:grid-cols-3">{[['Which reasoning held up?', heldUp, setHeldUp], ['Which evidence did you miss?', missed, setMissed], ['How should the thesis change?', change, setChange]].map(([label, value, setter]) => <label key={label as string} className={labelClass}>{label as string}<textarea aria-label={label as string} className="min-h-24 rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] p-3 text-sm" value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)} /></label>)}</div><button type="button" disabled={completedCaseIds.includes(caseId) || !heldUp || !missed || !change} onClick={save} className="min-h-10 w-fit rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white disabled:opacity-40">{completedCaseIds.includes(caseId) ? 'Reflection saved' : 'Save reflection'}</button></div>}
        </>}</section>;
};
