'use client';

import { useMemo, useState } from 'react';
import { calculateExpectancyV04, calculateRiskV04, isTradeConstructionV04, type RiskInputsV04, type TradeConstructionV04 } from '@/lib/learn/v0-4';

export type TradingRiskViewV4 = 'construction' | 'risk' | 'expectancy';
const inputClass = 'min-h-10 w-full rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] px-3 font-mono text-sm';
const labelClass = 'grid gap-1.5 text-xs font-semibold text-[var(--v7-text-secondary)]';

const RiskCalculator = ({ onComplete }: { onComplete: () => void }) => {
    const [inputs, setInputs] = useState<RiskInputsV04>({ direction: 'long', accountValue: 25000, riskPercent: 1, entry: 100, stop: 97.5, slippage: 0.1 }); const result = useMemo(() => calculateRiskV04(inputs), [inputs]);
    const update = (key: keyof RiskInputsV04, value: string) => setInputs((current) => ({ ...current, [key]: key === 'direction' ? value as RiskInputsV04['direction'] : Number(value) }));
    return <section data-testid="risk-calculator"><p className="text-[11px] font-bold uppercase text-[var(--v7-accent)]">Risk Calculator</p><h2 className="mt-2 text-xl font-bold">Account risk first, invalidation distance second.</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className={labelClass}>Direction<select aria-label="Risk direction" className={inputClass} value={inputs.direction} onChange={(event) => update('direction', event.target.value)}><option value="long">Long learning example</option><option value="short">Short learning example</option></select></label>{([['accountValue', 'Account value'], ['riskPercent', 'Max risk %'], ['entry', 'Entry'], ['stop', 'Invalidation / stop'], ['slippage', 'Estimated slippage / share']] as const).map(([key, label]) => <label key={key} className={labelClass}>{label}<input aria-label={label} type="number" step="0.01" className={inputClass} value={inputs[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</div>
        {result.error ? <p role="alert" className="mt-4 rounded-[6px] border border-red-500 p-3 text-sm text-red-600">{result.error}</p> : result.output && <div className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-[8px] border border-[var(--v7-border)] bg-[var(--v7-border)] lg:grid-cols-4">{[['Allowed risk', `$${result.output.allowedRisk.toFixed(2)}`], ['Risk / share', `$${result.output.riskPerShare.toFixed(2)}`], ['Position size', `${result.output.positionSize} shares`], ['Notional', `$${result.output.notional.toFixed(2)}`], ['Estimated loss', `$${result.output.estimatedLoss.toFixed(2)}`], ['1R price', `$${result.output.oneRTarget.toFixed(2)}`], ['2R price', `$${result.output.twoRTarget.toFixed(2)}`], ['Account risk used', `${(result.output.estimatedLoss / inputs.accountValue * 100).toFixed(2)}%`]].map(([label, value]) => <div key={label} className="bg-[var(--v7-surface-quiet)] p-3"><p className="text-[10px] uppercase text-[var(--v7-text-muted)]">{label}</p><p data-testid={label === 'Position size' ? 'risk-position-size' : undefined} className="mt-1 font-mono text-base font-bold">{value}</p></div>)}</div>}
        <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-[6px] border border-[var(--v7-border)] p-4"><p className="font-bold">Liquid large-cap example</p><p className="mt-2 text-xs leading-5 text-[var(--v7-text-muted)]">Bid $99.98 / ask $100.02. A market order still crosses the $0.04 spread and may slip.</p></div><div className="rounded-[6px] border border-[var(--v7-border)] p-4"><p className="font-bold">Thin instrument example</p><p className="mt-2 text-xs leading-5 text-[var(--v7-text-muted)]">Bid $98.80 / ask $100.50. Chart price is not an execution promise; size and order choice affect impact.</p></div></div><button type="button" disabled={!result.output} onClick={onComplete} className="mt-4 min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white disabled:opacity-40">Complete risk exercise</button>
    </section>;
};

const ExpectancyLab = ({ onComplete }: { onComplete: () => void }) => {
    const [a, setA] = useState({ winRatePercent: 75, averageWinnerR: 0.4, averageLoserR: 1.5 }); const [b, setB] = useState({ winRatePercent: 42, averageWinnerR: 2.4, averageLoserR: 0.9 }); const resultA = calculateExpectancyV04(a)!; const resultB = calculateExpectancyV04(b)!;
    const strategy = (name: string, value: typeof a, setter: typeof setA) => <article className="rounded-[8px] border border-[var(--v7-border)] p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-bold">Strategy {name}</h3><span className={`font-mono text-lg font-bold ${calculateExpectancyV04(value)!.expectancyR >= 0 ? 'text-[var(--v7-accent)]' : 'text-[var(--v7-risk)]'}`}>{calculateExpectancyV04(value)!.expectancyR.toFixed(2)}R</span></div><div className="mt-4 grid grid-cols-3 gap-2">{([['winRatePercent', 'Win %'], ['averageWinnerR', 'Avg win R'], ['averageLoserR', 'Avg loss R']] as const).map(([key, label]) => <label key={key} className={labelClass}>{label}<input aria-label={`${name} ${label}`} type="number" step="0.1" className={inputClass} value={value[key]} onChange={(event) => setter((current) => ({ ...current, [key]: Number(event.target.value) }))} /></label>)}</div></article>;
    return <section data-testid="expectancy-lab"><p className="text-[11px] font-bold uppercase text-[var(--v7-accent)]">Expectancy Lab</p><h2 className="mt-2 text-xl font-bold">Win rate is not edge.</h2><div className="mt-5 grid gap-4 lg:grid-cols-2">{strategy('A', a, setA)}{strategy('B', b, setB)}</div><div className="mt-4 rounded-[8px] border border-[var(--v7-border)] bg-[var(--v7-surface-quiet)] p-4 text-sm"><p>Strategy A profit factor: <strong>{resultA.profitFactor?.toFixed(2)}</strong>. Strategy B profit factor: <strong>{resultB.profitFactor?.toFixed(2)}</strong>.</p><p className="mt-2 text-xs text-[var(--v7-text-muted)]">Expectancy = win rate x average winner - loss rate x average loser. Distribution and costs still matter.</p></div><button type="button" onClick={onComplete} className="mt-4 min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white">Complete expectancy exercise</button></section>;
};

const TradeConstruction = ({ onComplete }: { onComplete: () => void }) => {
    const [plan, setPlan] = useState<TradeConstructionV04>({ decision: 'trade', context: '', setup: '', trigger: '', entry: 100, invalidation: 97.5, target: 105, horizon: '1-3 days', positionSize: 100, accountRisk: 250, confidence: 50, reasonNoTrade: '' }); const update = (key: keyof TradeConstructionV04, value: string) => setPlan((current) => ({ ...current, [key]: ['entry', 'invalidation', 'target', 'positionSize', 'accountRisk', 'confidence'].includes(key) ? Number(value) : value })); const valid = isTradeConstructionV04(plan);
    return <section data-testid="trade-construction"><p className="text-[11px] font-bold uppercase text-[var(--v7-accent)]">Trade Construction</p><h2 className="mt-2 text-xl font-bold">An indicator state is not a complete plan.</h2><div className="mt-4 inline-flex rounded-[6px] border border-[var(--v7-border)] p-1"><button type="button" aria-pressed={plan.decision === 'trade'} onClick={() => setPlan((current) => ({ ...current, decision: 'trade' }))} className={`min-h-10 rounded px-4 text-sm font-bold ${plan.decision === 'trade' ? 'bg-[var(--v7-accent-quiet)]' : ''}`}>Construct trade</button><button type="button" aria-pressed={plan.decision === 'no-trade'} onClick={() => setPlan((current) => ({ ...current, decision: 'no-trade' }))} className={`min-h-10 rounded px-4 text-sm font-bold ${plan.decision === 'no-trade' ? 'bg-[var(--v7-accent-quiet)]' : ''}`}>No Trade</button></div>
        <div className="mt-5 grid gap-3 md:grid-cols-2">{([['context', 'Context'], ['setup', 'Setup'], ['horizon', 'Time horizon']] as const).map(([key, label]) => <label key={key} className={labelClass}>{label}<textarea aria-label={`Plan ${label}`} className="min-h-20 rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] p-3 text-sm" value={String(plan[key])} onChange={(event) => update(key, event.target.value)} /></label>)}{plan.decision === 'no-trade' ? <label className={labelClass}>Reason not to trade<textarea aria-label="Plan reason not to trade" className="min-h-20 rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] p-3 text-sm" value={plan.reasonNoTrade} onChange={(event) => update('reasonNoTrade', event.target.value)} /></label> : <>{[['trigger', 'Trigger']].map(([key, label]) => <label key={key} className={labelClass}>{label}<textarea aria-label={`Plan ${label}`} className="min-h-20 rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] p-3 text-sm" value={String(plan[key as keyof TradeConstructionV04])} onChange={(event) => update(key as keyof TradeConstructionV04, event.target.value)} /></label>)}{([['entry', 'Entry'], ['invalidation', 'Invalidation'], ['target', 'Target'], ['positionSize', 'Position size'], ['accountRisk', 'Account risk']] as const).map(([key, label]) => <label key={key} className={labelClass}>{label}<input aria-label={`Plan ${label}`} type="number" className={inputClass} value={plan[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</>}</div><label className={`${labelClass} mt-4 max-w-md`}>Confidence: {plan.confidence}%<input aria-label="Plan confidence" type="range" min="0" max="100" value={plan.confidence} onChange={(event) => update('confidence', event.target.value)} /></label><button type="button" disabled={!valid} onClick={onComplete} className="mt-4 min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white disabled:opacity-40">Save construction exercise</button></section>;
};

export const LearnTradingRiskV4 = ({ view, onComplete }: { readonly view: TradingRiskViewV4; readonly onComplete: (id: string) => void }) => view === 'risk' ? <RiskCalculator onComplete={() => onComplete('risk')} /> : view === 'expectancy' ? <ExpectancyLab onComplete={() => onComplete('expectancy')} /> : <TradeConstruction onComplete={() => onComplete('construction')} />;
