'use client';

import { useEffect, useState } from 'react';
import { appendTradeEventV04, isTradeConstructionV04, parseTradeJournalV04, type TradeConstructionV04, type TradeEventTypeV04, type TradeJournalV04 } from '@/lib/learn/v0-4';

const journalKey = 'signal-learn-v0.4-trade-journal';
const inputClass = 'min-h-10 w-full rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] px-3 text-sm'; const labelClass = 'grid gap-1.5 text-xs font-semibold text-[var(--v7-text-secondary)]';
const emptyPlan: TradeConstructionV04 = { decision: 'trade', context: '', setup: '', trigger: '', entry: 100, invalidation: 97.5, target: 105, horizon: '1-3 days', positionSize: 100, accountRisk: 250, confidence: 50, reasonNoTrade: '' };

export const LearnTradeJournalV4 = ({ onComplete }: { readonly onComplete: () => void }) => {
    const [plan, setPlan] = useState<TradeConstructionV04>(emptyPlan); const [journal, setJournal] = useState<TradeJournalV04 | null>(null); const [ready, setReady] = useState(false); const [eventType, setEventType] = useState<TradeEventTypeV04>('hold'); const [eventReason, setEventReason] = useState(''); const [eventValue, setEventValue] = useState(''); const [debrief, setDebrief] = useState({ realizedR: '', adherence: '', wentWell: '', failed: '' });
    useEffect(() => { const timer = window.setTimeout(() => { try { const raw = localStorage.getItem(journalKey); setJournal(parseTradeJournalV04(raw ? JSON.parse(raw) : null)); } catch { setJournal(null); } setReady(true); }, 0); return () => clearTimeout(timer); }, []);
    useEffect(() => { if (!ready) return; if (journal) localStorage.setItem(journalKey, JSON.stringify(journal)); else localStorage.removeItem(journalKey); }, [journal, ready]);
    const update = (key: keyof TradeConstructionV04, value: string) => setPlan((current) => ({ ...current, [key]: ['entry', 'invalidation', 'target', 'positionSize', 'accountRisk', 'confidence'].includes(key) ? Number(value) : value }));
    const commit = () => { if (!isTradeConstructionV04(plan)) return; setJournal({ id: `trade-journal-${Date.now()}`, createdAt: new Date().toISOString(), original: { ...plan }, events: [], debrief: null }); };
    const append = () => { if (!journal || eventReason.trim().length < 3) return; const numeric = eventValue.trim() ? Number(eventValue) : null; if (numeric !== null && !Number.isFinite(numeric)) return; setJournal(appendTradeEventV04(journal, { id: `trade-event-${Date.now()}`, createdAt: new Date().toISOString(), type: eventType, reason: eventReason.trim(), value: numeric })); setEventReason(''); setEventValue(''); onComplete(); };
    const saveDebrief = () => { if (!journal || !debrief.adherence.trim() || !debrief.wentWell.trim() || !debrief.failed.trim()) return; const realizedR = debrief.realizedR.trim() ? Number(debrief.realizedR) : null; if (realizedR !== null && !Number.isFinite(realizedR)) return; setJournal({ ...journal, debrief: { realizedR, adherence: debrief.adherence.trim(), wentWell: debrief.wentWell.trim(), failed: debrief.failed.trim() } }); onComplete(); };
    if (journal) return <section data-testid="trade-journal"><p className="text-[11px] font-bold uppercase text-[var(--v7-accent)]">Trade Journal</p><h2 className="mt-2 text-xl font-bold">Original pre-trade plan</h2><div data-testid="trade-journal-original" className="mt-4 rounded-[8px] border border-[var(--v7-border)] bg-[var(--v7-surface-quiet)] p-4"><p className="text-xs text-[var(--v7-text-muted)]">Committed {new Date(journal.createdAt).toLocaleString()} · {journal.original.decision === 'no-trade' ? 'No Trade' : `${journal.original.positionSize} shares, $${journal.original.accountRisk.toFixed(2)} risk`}</p><p className="mt-3 text-sm"><strong>Context:</strong> {journal.original.context}</p><p className="mt-2 text-sm"><strong>Setup:</strong> {journal.original.setup}</p><p className="mt-2 text-sm"><strong>Trigger:</strong> {journal.original.decision === 'trade' ? journal.original.trigger : journal.original.reasonNoTrade}</p><p className="mt-2 text-sm"><strong>Invalidation:</strong> {journal.original.decision === 'trade' ? journal.original.invalidation : 'No position planned'}</p></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-3"><label className={labelClass}>Event<select aria-label="Journal event" className={inputClass} value={eventType} onChange={(event) => setEventType(event.target.value as TradeEventTypeV04)}><option value="hold">Hold</option><option value="partial-exit">Partial exit</option><option value="adjust-stop">Adjust stop</option><option value="exit">Exit</option><option value="cancel-thesis">Cancel thesis</option></select></label><label className={labelClass}>Reason<input aria-label="Journal event reason" className={inputClass} value={eventReason} onChange={(event) => setEventReason(event.target.value)} /></label><label className={labelClass}>Price / size if relevant<input aria-label="Journal event value" type="number" className={inputClass} value={eventValue} onChange={(event) => setEventValue(event.target.value)} /></label></div><button type="button" onClick={append} className="mt-3 min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white">Append event</button><div className="mt-4 grid gap-2">{journal.events.map((event, index) => <article key={event.id} className="border-l-2 border-[var(--v7-accent)] pl-4"><p className="text-[10px] uppercase text-[var(--v7-text-muted)]">Event {index + 1} · {event.type}</p><p className="mt-1 text-sm">{event.reason}{event.value === null ? '' : ` at ${event.value}`}</p></article>)}</div>
        <h3 className="mt-6 text-base font-bold">Post-trade debrief</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{([['realizedR', 'Realized R'], ['adherence', 'Rule adherence'], ['wentWell', 'What went well'], ['failed', 'What failed']] as const).map(([key, label]) => <label key={key} className={labelClass}>{label}{key === 'realizedR' ? <input aria-label={label} type="number" step="0.1" className={inputClass} value={debrief[key]} onChange={(event) => setDebrief((current) => ({ ...current, [key]: event.target.value }))} /> : <textarea aria-label={label} className="min-h-20 rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] p-3 text-sm" value={debrief[key]} onChange={(event) => setDebrief((current) => ({ ...current, [key]: event.target.value }))} />}</label>)}</div><p className="mt-3 text-xs text-[var(--v7-text-muted)]">Process review compares the plan with events. P&amp;L does not overwrite the original or define adherence.</p><button type="button" onClick={saveDebrief} className="mt-3 min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white">Save debrief</button>
    </section>;
    return <section data-testid="trade-journal-create"><p className="text-[11px] font-bold uppercase text-[var(--v7-accent)]">Trade Journal</p><h2 className="mt-2 text-xl font-bold">Commit before outcome.</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{([['context', 'Context'], ['setup', 'Setup'], ['trigger', 'Trigger'], ['horizon', 'Time horizon']] as const).map(([key, label]) => <label key={key} className={labelClass}>{label}<textarea aria-label={`Journal ${label}`} className="min-h-20 rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] p-3 text-sm" value={String(plan[key])} onChange={(event) => update(key, event.target.value)} /></label>)}{([['entry', 'Entry'], ['invalidation', 'Invalidation'], ['target', 'Target'], ['positionSize', 'Position size'], ['accountRisk', 'Account risk']] as const).map(([key, label]) => <label key={key} className={labelClass}>{label}<input aria-label={`Journal ${label}`} type="number" className={inputClass} value={plan[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</div><label className={`${labelClass} mt-4 max-w-md`}>Expected confidence: {plan.confidence}%<input aria-label="Journal confidence" type="range" min="0" max="100" value={plan.confidence} onChange={(event) => update('confidence', event.target.value)} /></label><button type="button" disabled={!isTradeConstructionV04(plan)} onClick={commit} className="mt-4 min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white disabled:opacity-40">Commit pre-trade plan</button></section>;
};
