'use client';

import { useMemo, useState } from 'react';
import { runBacktestV04, strategyLabCandlesV04, type BacktestInputsV04 } from '@/lib/learn/v0-4';

const inputClass = 'min-h-10 w-full rounded-[6px] border border-[var(--v7-border)] bg-[var(--v7-surface)] px-3 font-mono text-sm';
export const LearnStrategyLabV4 = ({ onComplete }: { readonly onComplete: () => void }) => {
    const [inputs, setInputs] = useState<BacktestInputsV04>({ fastLookback: 5, slowLookback: 14, holdingBars: 5, costBps: 4, slippageBps: 6 }); const result = useMemo(() => runBacktestV04(strategyLabCandlesV04, inputs), [inputs]); const neighbors = useMemo(() => [-1, 0, 1].map((change) => ({ fast: inputs.fastLookback + change, result: runBacktestV04(strategyLabCandlesV04, { ...inputs, fastLookback: inputs.fastLookback + change }) })), [inputs]);
    const update = (key: keyof BacktestInputsV04, value: string) => setInputs((current) => ({ ...current, [key]: Number(value) }));
    return <section data-testid="strategy-lab"><p className="text-[11px] font-bold uppercase text-[var(--v7-accent)]">Strategy Lab</p><h2 className="mt-2 text-xl font-bold">Define first. Test point-in-time. Inspect fragility.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--v7-text-secondary)]">Educational hypothesis: enter at the next bar&apos;s open after a fast SMA crosses above a slow SMA, then exit after a fixed number of bars. Future bars never participate in the signal.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{([['fastLookback', 'Fast lookback'], ['slowLookback', 'Slow lookback'], ['holdingBars', 'Holding bars'], ['costBps', 'Fees bps'], ['slippageBps', 'Slippage bps']] as const).map(([key, label]) => <label key={key} className="grid gap-1.5 text-xs font-semibold">{label}<input aria-label={label} type="number" className={inputClass} value={inputs[key]} onChange={(event) => update(key, event.target.value)} /></label>)}</div>
        {result ? <><div className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-[8px] border border-[var(--v7-border)] bg-[var(--v7-border)] lg:grid-cols-6">{[['Samples', result.sampleCount], ['Win rate', `${result.winRate.toFixed(1)}%`], ['Average / expectancy', `${result.averageR.toFixed(2)}R`], ['Profit factor', result.profitFactor?.toFixed(2) ?? 'N/A'], ['Max drawdown', `${result.maxDrawdownR.toFixed(2)}R`], ['Costs', `${inputs.costBps + inputs.slippageBps} bps`]].map(([label, value]) => <div key={label} className="bg-[var(--v7-surface-quiet)] p-3"><p className="text-[10px] uppercase text-[var(--v7-text-muted)]">{label}</p><p className="mt-1 font-mono text-base font-bold">{value}</p></div>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-[8px] border border-[var(--v7-border)] p-4"><h3 className="font-bold">Required warnings</h3><ul className="mt-2 grid gap-1 text-xs leading-5">{result.warnings.map((warning) => <li key={warning}>- {warning}</li>)}</ul></div><div className="rounded-[8px] border border-[var(--v7-border)] p-4"><h3 className="font-bold">Parameter sensitivity</h3><div className="mt-2 grid grid-cols-3 gap-2">{neighbors.map((neighbor) => <div key={neighbor.fast} className="rounded border border-[var(--v7-border)] p-2 text-center"><p className="text-[10px] uppercase">Fast {neighbor.fast}</p><p className="mt-1 font-mono text-sm font-bold">{neighbor.result ? `${neighbor.result.averageR.toFixed(2)}R` : 'Invalid'}</p></div>)}</div><p className="mt-2 text-xs text-[var(--v7-text-muted)]">Small parameter changes expose fragility; do not silently search until one curve looks profitable.</p></div></div></> : <p role="alert" className="mt-4 text-sm text-red-600">Use a fast lookback below the slow lookback and non-negative cost assumptions.</p>}
        <button type="button" disabled={!result} onClick={onComplete} className="mt-4 min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white disabled:opacity-40">Complete strategy exercise</button>
    </section>;
};
