'use client';

import { useMemo, useState } from 'react';
import { calculateAtrV04, calculateRsiV04, tradingLabCandlesV04 } from '@/lib/learn/v0-4';
import { TradingCandleChartV4 } from './TradingCandleChartV4';

export const LearnTradingChartLabV4 = ({ onComplete }: { readonly onComplete: () => void }) => {
    const [classification, setClassification] = useState(''); const [revealed, setRevealed] = useState(false); const [sma, setSma] = useState(10); const [ema, setEma] = useState(6); const [showVwap, setShowVwap] = useState(true);
    const rsi = useMemo(() => calculateRsiV04(tradingLabCandlesV04, 14).at(-1)?.value ?? null, []); const atr = useMemo(() => calculateAtrV04(tradingLabCandlesV04, 14).at(-1)?.value ?? null, []);
    return <section data-testid="trading-chart-lab"><p className="text-[11px] font-bold uppercase text-[var(--v7-accent)]">Price and indicator lab</p><h2 className="mt-2 text-xl font-bold text-[var(--v7-text)]">Start with structure. Add transforms as context.</h2><div className="mt-4"><TradingCandleChartV4 candles={tradingLabCandlesV04} smaPeriod={sma} emaPeriod={ema} showVwap={showVwap} label="Illustrative daily candlestick chart with volume and learner-selected overlays" /></div>
        <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]"><div><p className="text-xs font-bold text-[var(--v7-text-secondary)]">Classify the unlabeled structure before reveal</p><div className="mt-2 flex flex-wrap gap-2">{['Uptrend', 'Downtrend', 'Range / transition'].map((option) => <button key={option} type="button" aria-pressed={classification === option} onClick={() => setClassification(option)} className={`min-h-10 rounded-[6px] border px-3 text-xs font-semibold ${classification === option ? 'border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)]' : 'border-[var(--v7-border)]'}`}>{option}</button>)}<button type="button" disabled={!classification} onClick={() => setRevealed(true)} className="min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-3 text-xs font-bold text-white disabled:opacity-40">Reveal annotation</button></div>{revealed && <p data-testid="structure-reveal" className="mt-3 rounded-[6px] border border-[var(--v7-border)] p-3 text-xs leading-5">The fixture changes regime: early advances give way to a transition and renewed rise. A single label loses information; mark reaction zones and define invalidation.</p>}</div><dl className="grid grid-cols-2 gap-2"><div className="rounded-[6px] border border-[var(--v7-border)] p-3"><dt className="text-[10px] uppercase text-[var(--v7-text-muted)]">RSI(14)</dt><dd data-testid="chart-rsi" className="mt-1 font-mono text-lg font-bold">{rsi?.toFixed(1) ?? 'N/A'}</dd></div><div className="rounded-[6px] border border-[var(--v7-border)] p-3"><dt className="text-[10px] uppercase text-[var(--v7-text-muted)]">ATR(14)</dt><dd data-testid="chart-atr" className="mt-1 font-mono text-lg font-bold">{atr?.toFixed(2) ?? 'N/A'}</dd></div></dl></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-xs font-semibold">SMA lookback: {sma}<input aria-label="SMA lookback" type="range" min="3" max="30" value={sma} onChange={(event) => setSma(Number(event.target.value))} /></label><label className="grid gap-1 text-xs font-semibold">EMA lookback: {ema}<input aria-label="EMA lookback" type="range" min="3" max="30" value={ema} onChange={(event) => setEma(Number(event.target.value))} /></label><label className="flex min-h-10 items-center gap-2 text-xs font-semibold"><input aria-label="Show VWAP" type="checkbox" checked={showVwap} onChange={(event) => setShowVwap(event.target.checked)} />Show anchored VWAP context</label></div>
        <div className="mt-4 grid gap-3 sm:grid-cols-3"><p className="rounded-[6px] border border-[var(--v7-border)] p-3 text-xs leading-5"><strong>Momentum:</strong> overbought is a calculation state; persistent trends can remain elevated.</p><p className="rounded-[6px] border border-[var(--v7-border)] p-3 text-xs leading-5"><strong>Participation:</strong> compare relative volume with the move; expansion does not validate every breakout.</p><p className="rounded-[6px] border border-[var(--v7-border)] p-3 text-xs leading-5"><strong>Volatility:</strong> ATR changes the meaning of a fixed-dollar stop and therefore position size.</p></div><button type="button" disabled={!revealed} onClick={onComplete} className="mt-4 min-h-10 rounded-[6px] bg-[var(--v7-accent)] px-4 text-sm font-bold text-white disabled:opacity-40">Complete chart lab</button>
    </section>;
};
