'use client';

import { useEffect, useMemo, useState } from 'react';
import {
    calculateExpectancyV04,
    calculatePositionSizeV04,
    calculateProfitFactorV04,
    calculateRMultipleV04,
    tradingModulesV04,
    type TradingModuleIdV04,
} from '@/lib/learn/v0-4';

const progressKey = 'signal-learn-v0.4-progress';

const Card = ({ title, children, tone = 'default' }: { readonly title: string; readonly children: React.ReactNode; readonly tone?: 'default' | 'accent' | 'risk' | 'caution' }) => {
    const classes = tone === 'accent' ? 'border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)]'
        : tone === 'risk' ? 'border-[var(--v7-risk)] bg-[var(--v7-risk-quiet)]'
            : tone === 'caution' ? 'border-[var(--v7-caution)] bg-[var(--v7-caution-quiet)]'
                : 'border-[var(--v7-border)] bg-[var(--v7-surface-quiet)]';
    return <article className={`rounded-[11px] border p-4 ${classes}`}><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-[var(--v7-text-muted)]">{title}</p><div className="mt-2 text-sm leading-6 text-[var(--v7-text-secondary)]">{children}</div></article>;
};

const NumberField = ({ label, value, onChange, suffix, step = '1' }: { readonly label: string; readonly value: number; readonly onChange: (value: number) => void; readonly suffix?: string; readonly step?: string }) => <label className="grid gap-1.5 text-xs font-semibold text-[var(--v7-text-secondary)]">{label}<span className="flex min-h-10 items-center rounded-[9px] border border-[var(--v7-border)] px-3 focus-within:border-[var(--v7-accent)]"><input type="number" step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} className="min-w-0 flex-1 bg-transparent font-mono text-sm text-[var(--v7-text)] outline-none" />{suffix ? <span className="ml-1 text-[var(--v7-text-muted)]">{suffix}</span> : null}</span></label>;
const fmt = (value: number | null, suffix = '', digits = 2) => value === null || !Number.isFinite(value) ? 'N/A' : `${new Intl.NumberFormat('en-US', { maximumFractionDigits: digits }).format(value)}${suffix}`;

const PositionSizingLab = () => {
    const [account, setAccount] = useState(10_000);
    const [risk, setRisk] = useState(1);
    const [entry, setEntry] = useState(100);
    const [stop, setStop] = useState(95);
    const [slippage, setSlippage] = useState(0);
    const result = calculatePositionSizeV04(account, risk, entry, stop, slippage);
    return <div data-testid="position-size-lab-v4" className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="Account value" value={account} onChange={setAccount} suffix="$" step="100" /><NumberField label="Max risk" value={risk} onChange={setRisk} suffix="%" step="0.25" /><NumberField label="Entry" value={entry} onChange={setEntry} suffix="$" step="0.5" /><NumberField label="Invalidation stop" value={stop} onChange={setStop} suffix="$" step="0.5" /><NumberField label="Slippage allowance / share" value={slippage} onChange={setSlippage} suffix="$" step="0.05" /></div>{result.valid ? <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{[
        ['Risk budget', `$${fmt(result.riskBudget)}`], ['Risk / share', `$${fmt(result.riskPerShare)}`], ['Position size', `${result.shares ?? 0} shares`], ['Estimated loss at invalidation', `$${fmt(result.estimatedLoss)}`],
    ].map(([label, value]) => <div key={label} className="rounded-[9px] border border-[var(--v7-border)] bg-[var(--v7-surface-quiet)] p-3"><p className="text-[10px] uppercase tracking-[0.08em] text-[var(--v7-text-muted)]">{label}</p><p className="mt-1 font-mono text-sm font-bold">{value}</p></div>)}</div> : <p role="alert" data-testid="position-size-error-v4" className="mt-4 rounded-[9px] border border-[var(--v7-risk)] bg-[var(--v7-risk-quiet)] p-3 text-sm text-[var(--v7-text-secondary)]">{result.error}</p>}</div><Card title="Sizing sequence" tone="accent"><strong className="text-[var(--v7-text)]">Account risk → invalidation distance → position size.</strong><p className="mt-2">The size is derived from the stop that invalidates the setup, not from how strongly you feel about the trade.</p><p className="mt-2 text-xs">v0.4 calculator: long-practice only. A stop at or above entry is rejected instead of guessed.</p></Card></div>;
};

const ExpectancyLab = () => {
    const [winRate, setWinRate] = useState(40);
    const [winner, setWinner] = useState(2);
    const [loser, setLoser] = useState(1);
    const expectancy = calculateExpectancyV04(winRate, winner, loser);
    const profitFactor = calculateProfitFactorV04(winRate, winner, loser);
    return <div data-testid="expectancy-lab-v4" className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><div><div className="grid gap-3 sm:grid-cols-3"><NumberField label="Win rate" value={winRate} onChange={setWinRate} suffix="%" /><NumberField label="Average winner" value={winner} onChange={setWinner} suffix="R" step="0.1" /><NumberField label="Average loser" value={loser} onChange={setLoser} suffix="R" step="0.1" /></div><div className="mt-4 grid gap-2 sm:grid-cols-2"><div className="rounded-[9px] border border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)] p-3"><p className="text-[10px] uppercase tracking-[0.08em] text-[var(--v7-text-muted)]">Expectancy</p><p data-testid="expectancy-result-v4" className="mt-1 font-mono text-lg font-bold">{fmt(expectancy, 'R')}</p></div><div className="rounded-[9px] border border-[var(--v7-border)] bg-[var(--v7-surface-quiet)] p-3"><p className="text-[10px] uppercase tracking-[0.08em] text-[var(--v7-text-muted)]">Profit factor proxy</p><p className="mt-1 font-mono text-lg font-bold">{fmt(profitFactor, '×')}</p></div></div></div><Card title="Win rate is not edge" tone="accent">A 40% win-rate strategy can have positive expectancy if average winners are sufficiently larger than average losses. One winning trade proves almost nothing about the process.</Card></div>;
};

const RLab = () => {
    const [entry, setEntry] = useState(100);
    const [stop, setStop] = useState(95);
    const [exit, setExit] = useState(112);
    const r = calculateRMultipleV04(entry, stop, exit);
    return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="grid gap-3 sm:grid-cols-3"><NumberField label="Entry" value={entry} onChange={setEntry} suffix="$" /><NumberField label="Stop" value={stop} onChange={setStop} suffix="$" /><NumberField label="Exit" value={exit} onChange={setExit} suffix="$" /></div><Card title="Outcome in risk units" tone="accent"><span className="font-mono text-2xl font-bold text-[var(--v7-text)]">{fmt(r, 'R')}</span><p className="mt-2">R normalizes outcomes by the amount you planned to lose if the setup was invalidated.</p></Card></div>;
};

const Concept = ({ id }: { readonly id: TradingModuleIdV04 }) => {
    if (id === 'position-sizing') return <PositionSizingLab />;
    if (id === 'expectancy') return <ExpectancyLab />;
    if (id === 'risk-reward') return <RLab />;
    if (id === 'price-structure') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Trend" tone="accent">Higher highs and higher lows describe an observed uptrend; lower highs and lower lows describe an observed downtrend. Description is not a guarantee the structure persists.</Card><Card title="Range">A market can rotate between boundaries without a durable directional trend. Failed breakouts are information, not proof the opposite side must win.</Card><Card title="Start with price">Read structure before adding transformed indicators. Otherwise indicators can make the same underlying price history look like multiple independent signals.</Card><Card title="No prediction shortcut" tone="risk">“Breakout” names a price event. It does not tell you the probability, invalidation, or appropriate position size by itself.</Card></div>;
    if (id === 'support-resistance') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Reaction zones" tone="accent">Prior highs, lows, range boundaries, and failed breaks can mark areas where participants previously reacted.</Card><Card title="Not an exact wall" tone="risk">Support at $100 does not mean $100.00 must hold. Define an area and the observable condition that would invalidate the setup.</Card><Card title="Context">Repeated tests, volatility, volume, trend, and time since the prior reaction can change how useful the area is.</Card><Card title="Practice">Historical Replay asks for an invalidation condition before showing later bars.</Card></div>;
    if (id === 'moving-averages') return <div className="grid gap-3 sm:grid-cols-2"><Card title="SMA / EMA" tone="accent">Both summarize historical prices. EMA weights recent observations more heavily; neither has independent knowledge of the next price.</Card><Card title="Lag">Longer lookbacks generally react more slowly. Faster response also means more sensitivity to short-lived moves.</Card><Card title="Crossovers">A crossover describes the relationship between two lagging transforms. It is not automatically an entry signal.</Card><Card title="Same data" tone="caution">Price, SMA, EMA, RSI and MACD are not five independent pieces of evidence when they are all derived from the same price history.</Card></div>;
    if (id === 'momentum') return <div className="grid gap-3 sm:grid-cols-2"><Card title="RSI" tone="accent">RSI summarizes recent gain/loss momentum over its lookback. High RSI can persist during a strong trend.</Card><Card title="Overbought ≠ sell" tone="risk">RSI above 70 is a calculation state, not a deterministic short instruction. Trend context and invalidation still matter.</Card><Card title="MACD">MACD compares exponential moving averages; its signal line is another transformation of that derived series.</Card><Card title="Divergence">Divergence can highlight changing momentum, but it can persist or fail. Treat it as context, not a forecast guarantee.</Card></div>;
    if (id === 'volume') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Participation" tone="accent">Volume helps describe how much trading activity accompanied a price move.</Card><Card title="Relative context">Raw volume is more useful when compared with the instrument’s own normal activity and the specific session/event context.</Card><Card title="No universal confirmation" tone="risk">High volume does not make every breakout valid, and low volume does not guarantee failure.</Card><Card title="Daily source limit">Signal v0.4 uses daily aggregated volume for learning. It does not claim order-level participation.</Card></div>;
    if (id === 'vwap') return <div className="grid gap-3 sm:grid-cols-2"><Card title="VWAP intuition" tone="accent">VWAP is a volume-weighted reference price. Anchored VWAP changes the starting point to a chosen event/range.</Card><Card title="Above ≠ buy" tone="risk">Price above VWAP is context about location relative to traded volume, not a Buy rule.</Card><Card title="Anchor choice">Anchored VWAP can change materially depending on the anchor. Explain why an anchor is relevant rather than optimizing it after seeing the outcome.</Card><Card title="Signal implementation">Research’s range-start anchored VWAP is calculated chronologically from the selected daily series.</Card></div>;
    if (id === 'volatility') return <div className="grid gap-3 sm:grid-cols-2"><Card title="ATR" tone="accent">ATR summarizes recent true range. A $1 move means something different when ATR is $0.50 versus $8.</Card><Card title="Stop context">A fixed-dollar stop can be extremely tight in one volatility regime and very loose in another.</Card><Card title="Sizing link">Wider invalidation distance means fewer shares for the same account risk.</Card><Card title="Volatility ≠ direction" tone="risk">High volatility describes magnitude, not whether the next move should be up or down.</Card></div>;
    if (id === 'execution') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Bid / ask / spread" tone="accent">Executable prices exist around the displayed market. Spread and liquidity affect the difference between chart price and fill.</Card><Card title="Orders">Market orders prioritize execution; limit orders constrain price but may not fill; stops become active after a trigger according to broker rules.</Card><Card title="Slippage">Fast markets and thin liquidity can produce fills worse than a backtest’s ideal price.</Card><Card title="Daily replay limit" tone="caution">v0.4 replay cannot reconstruct intraday queue position or spread from daily OHLCV and says so explicitly.</Card></div>;
    if (id === 'trade-construction') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Complete plan" tone="accent">Context → Setup → Trigger → Entry → Invalidation → Target → Horizon.</Card><Card title="Invalidation first">The stop should represent where the trade idea becomes wrong, then position size adapts to that distance.</Card><Card title="No Trade is valid">A disciplined process includes situations where evidence is insufficient and the correct action is to do nothing.</Card><Card title="Indicator-only plan" tone="risk">“RSI is oversold” is not a complete trade plan because it lacks context, trigger, invalidation, target and risk.</Card></div>;
    if (id === 'trade-management') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Plan before emotion" tone="accent">Define what would justify a partial exit, trailing stop, time stop, or thesis cancellation before the situation becomes stressful.</Card><Card title="Stop widening" tone="risk">Moving a stop farther away after entry increases planned risk unless position size changes. Ask whether new evidence truly changed invalidation.</Card><Card title="Break-even moves">Moving to break-even can reduce loss risk but can also exit trades that still fit the original setup.</Card><Card title="Journal changes">Record management changes and why they happened so later review distinguishes plan from improvisation.</Card></div>;
    if (id === 'backtesting') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Define before testing" tone="accent">Specify universe, timeframe, entry, exit, invalidation, sizing, and costs before judging results.</Card><Card title="Look-ahead bias" tone="risk">A historical decision cannot access future bars, future indicators, later constituents, or later event knowledge.</Card><Card title="Costs">Fees, spread, and slippage can erase a small theoretical edge.</Card><Card title="Out-of-sample">Reserve data or later periods to test whether the rule survives outside the data used to design it.</Card></div>;
    if (id === 'statistics') return <div className="grid gap-3 sm:grid-cols-2"><Card title="Distribution" tone="accent">Track win rate, average winner, average loser, expectancy, profit factor, and drawdown together.</Card><Card title="Total return alone" tone="risk">One cumulative return number can hide a fragile path, extreme drawdown, or one outlier trade.</Card><Card title="R units">R makes outcomes comparable across trades with different prices and stop distances.</Card><Card title="Sample size">A handful of trades can look exceptional by chance. Statistical confidence requires enough independent observations.</Card></div>;
    return <div className="grid gap-3 sm:grid-cols-2"><Card title="Parameter mining" tone="risk">Trying many indicator periods until one looks perfect can fit noise rather than discover a durable edge.</Card><Card title="Robustness" tone="accent">A credible strategy should not collapse when a reasonable parameter changes slightly or when tested in a nearby period.</Card><Card title="Regimes">A rule may depend on volatility, trend, liquidity, or macro regime. Measure where it worked rather than assuming universality.</Card><Card title="False discovery">The more strategies you test, the more likely one looks impressive by luck. Keep a hypothesis and out-of-sample boundary.</Card></div>;
};

export const TradingTrackV4 = () => {
    const [moduleId, setModuleId] = useState<TradingModuleIdV04>('price-structure');
    const [completed, setCompleted] = useState<TradingModuleIdV04[]>([]);
    const [ready, setReady] = useState(false);
    useEffect(() => {
        const timer = window.setTimeout(() => {
            try {
                const parsed: unknown = JSON.parse(window.localStorage.getItem(progressKey) ?? '[]');
                if (Array.isArray(parsed)) setCompleted(parsed.filter((value): value is TradingModuleIdV04 => typeof value === 'string' && tradingModulesV04.some((item) => item.id === value)));
            } catch { setCompleted([]); }
            setReady(true);
        }, 0);
        return () => window.clearTimeout(timer);
    }, []);
    useEffect(() => { if (ready) window.localStorage.setItem(progressKey, JSON.stringify(completed)); }, [completed, ready]);
    const selected = useMemo(() => tradingModulesV04.find((item) => item.id === moduleId) ?? tradingModulesV04[0], [moduleId]);
    const toggle = () => setCompleted((current) => current.includes(moduleId) ? current.filter((id) => id !== moduleId) : [...current, moduleId]);
    return <div data-testid="trading-track-v4" className="grid gap-4 lg:grid-cols-[275px_minmax(0,1fr)]"><aside className="min-w-0 rounded-[11px] border border-[var(--v7-border)] bg-[var(--v7-surface-quiet)] p-3 lg:self-start"><div className="flex items-center justify-between px-2 pb-2"><p className="text-[11px] font-bold uppercase tracking-[0.1em] text-[var(--v7-text-muted)]">v0.4 path</p><span className="font-mono text-[11px] text-[var(--v7-text-muted)]">{completed.length}/{tradingModulesV04.length}</span></div><div className="research-scrollbar flex gap-2 overflow-x-auto lg:grid lg:overflow-visible">{tradingModulesV04.map((item) => <button key={item.id} type="button" aria-pressed={item.id === moduleId} onClick={() => setModuleId(item.id)} className={`min-h-11 min-w-[225px] rounded-[9px] border px-3 py-2 text-left lg:min-w-0 ${item.id === moduleId ? 'border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)]' : 'border-transparent hover:border-[var(--v7-border)] hover:bg-[var(--v7-surface)]'}`}><span className="flex items-center justify-between gap-2"><span className="text-xs font-semibold text-[var(--v7-text)]">{item.eyebrow} · {item.title}</span><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${completed.includes(item.id) ? 'bg-[var(--v7-accent)]' : 'border border-[var(--v7-border-strong)]'}`} /></span></button>)}</div></aside><section className="rounded-[11px] border border-[var(--v7-border)] bg-[var(--v7-surface)] p-4 sm:p-5 lg:p-6"><div className="flex flex-col gap-4 border-b border-[var(--v7-border)] pb-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.12em] text-[var(--v7-accent)]">Module {selected.eyebrow}</p><h2 className="mt-1 text-xl font-bold">{selected.title}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-[var(--v7-text-secondary)]">{selected.objective}</p></div><button type="button" aria-pressed={completed.includes(moduleId)} onClick={toggle} className={`min-h-10 rounded-[9px] border px-4 text-sm font-semibold ${completed.includes(moduleId) ? 'border-[var(--v7-accent)] bg-[var(--v7-accent-quiet)]' : 'border-[var(--v7-border)] text-[var(--v7-text-secondary)]'}`}>{completed.includes(moduleId) ? 'Understood ✓' : 'Mark understood'}</button></div><div className="pt-5"><Concept id={moduleId} /></div></section></div>;
};
