'use client';

import { useMemo } from 'react';
import { calculateEmaV04, calculateSmaV04, calculateVwapV04, type CandleV04 } from '@/lib/learn/v0-4';

type Props = { readonly candles: readonly CandleV04[]; readonly smaPeriod?: number | null; readonly emaPeriod?: number | null; readonly showVwap?: boolean; readonly label: string };

export const TradingCandleChartV4 = ({ candles, smaPeriod = null, emaPeriod = null, showVwap = false, label }: Props) => {
    const geometry = useMemo(() => {
        const width = 900; const priceTop = 24; const priceBottom = 300; const volumeTop = 322; const volumeBottom = 390; const step = candles.length ? (width - 50) / candles.length : 1; const minimum = Math.min(...candles.map((candle) => candle.low)); const maximum = Math.max(...candles.map((candle) => candle.high)); const range = Math.max(maximum - minimum, 1); const maxVolume = Math.max(...candles.map((candle) => candle.volume), 1);
        const x = (index: number) => 32 + step * index + step / 2; const y = (value: number) => priceBottom - ((value - minimum) / range) * (priceBottom - priceTop); const overlay = (points: readonly { value: number | null }[]) => points.map((point, index) => point.value === null ? null : `${x(index)},${y(point.value)}`).filter((point): point is string => point !== null).join(' ');
        return { width, priceTop, priceBottom, volumeTop, volumeBottom, step, minimum, maximum, maxVolume, x, y, sma: smaPeriod ? overlay(calculateSmaV04(candles, smaPeriod)) : '', ema: emaPeriod ? overlay(calculateEmaV04(candles, emaPeriod)) : '', vwap: showVwap ? overlay(calculateVwapV04(candles)) : '' };
    }, [candles, emaPeriod, showVwap, smaPeriod]);
    if (candles.length === 0) return <div className="flex aspect-[9/4] items-center justify-center rounded-[8px] border border-[var(--v7-border)] text-sm text-[var(--v7-text-muted)]">No candles available.</div>;
    return <div className="overflow-hidden rounded-[8px] border border-[var(--v7-border)] bg-[var(--v7-surface-quiet)]" data-testid="trading-candle-chart"><svg role="img" aria-label={label} viewBox="0 0 900 410" className="block aspect-[9/4] min-h-[220px] w-full"><rect width="900" height="410" fill="var(--v7-surface-quiet)" />
        {[0, 1, 2, 3, 4].map((line) => { const y = geometry.priceTop + (geometry.priceBottom - geometry.priceTop) * line / 4; const value = geometry.maximum - (geometry.maximum - geometry.minimum) * line / 4; return <g key={line}><line x1="28" x2="890" y1={y} y2={y} stroke="var(--v7-border)" strokeWidth="1" /><text x="34" y={y - 4} fill="var(--v7-text-muted)" fontSize="11">${value.toFixed(1)}</text></g>; })}
        {candles.map((candle, index) => { const rising = candle.close >= candle.open; const color = rising ? 'var(--v7-accent)' : 'var(--v7-risk)'; const x = geometry.x(index); const bodyTop = geometry.y(Math.max(candle.open, candle.close)); const bodyBottom = geometry.y(Math.min(candle.open, candle.close)); const volumeHeight = candle.volume / geometry.maxVolume * (geometry.volumeBottom - geometry.volumeTop); return <g key={candle.openTime}><title>{`${candle.closeTime}: open ${candle.open.toFixed(2)}, high ${candle.high.toFixed(2)}, low ${candle.low.toFixed(2)}, close ${candle.close.toFixed(2)}, volume ${candle.volume}`}</title><line x1={x} x2={x} y1={geometry.y(candle.high)} y2={geometry.y(candle.low)} stroke={color} strokeWidth="2" /><rect x={x - Math.max(2, geometry.step * 0.28)} y={bodyTop} width={Math.max(4, geometry.step * 0.56)} height={Math.max(bodyBottom - bodyTop, 2)} fill={color} /><rect x={x - Math.max(2, geometry.step * 0.28)} y={geometry.volumeBottom - volumeHeight} width={Math.max(4, geometry.step * 0.56)} height={volumeHeight} fill={color} opacity="0.45" /></g>; })}
        {geometry.sma && <polyline points={geometry.sma} fill="none" stroke="#2563eb" strokeWidth="2.5" data-testid="sma-line" />}{geometry.ema && <polyline points={geometry.ema} fill="none" stroke="#d97706" strokeWidth="2.5" data-testid="ema-line" />}{geometry.vwap && <polyline points={geometry.vwap} fill="none" stroke="#9333ea" strokeWidth="2.5" strokeDasharray="6 4" data-testid="vwap-line" />}
        <text x="34" y="314" fill="var(--v7-text-muted)" fontSize="11">Volume</text><text x="890" y="404" textAnchor="end" fill="var(--v7-text-muted)" fontSize="11">Known through {new Date(candles.at(-1)!.knownAsOf).toLocaleString()}</text>
    </svg></div>;
};
